### Create characters
POST https://ded-companion.onrender.com/characters
Content-Type: application/json

{
    "name": "veteran",
    "level": 3,
    "class": "warrior",
    "armor_class": 16,
    "hitpoints": 20,
    "attributes": {
       "for": 10,
       "dex": 12,
       "con": 14,
       "int": 16,
       "wis": 8,
       "car": 18
}
}

### List characters
GET https://ded-companion.onrender.com/characters

### Search usign Quey parameters

GET https://ded-companion.onrender.com/characters?search=newbie

### Update Character

PUT https://ded-companion.onrender.com/characters/d05c02e4-5f59-4cbe-b28c-8655608c0138
Content-Type: application/json

{
    "name": "Cyrus",
    "level": 1,
    "class": "warrior",
    "armor_class": 18,
    "hitpoints": 32,
    "attributes": {
       "for": 14,
       "dex": 12,
       "con": 14,
       "int": 16,
       "wis": 8,
       "car": 18
}
}

### Delete Character

DELETE https://ded-companion.onrender.com/characters/d05c02e4-5f59-4cbe-b28c-8655608c0138

### Create rooms
POST https://localhost:3333/rooms
Content-Type: application/json

{
    "room_name": "primeira mesa!",
}
