### Create characters
POST http://localhost:3333/characters
Content-Type: application/json

{
    "name": "veteran",
    "level": 3,
    "class": "warrior"
}

### List characters
GET http://localhost:3333/characters

### Search usign Quey parameters

GET http://localhost:3333/characters?search=newbie

### Update Character

PUT http://localhost:3333/characters/163b51b6-741e-4222-bce7-2b67a1d74f5f
Content-Type: application/json

{
  "name": "Veteran",
  "level": 3,
  "class": "Warrior"
}

### Delete Character

DELETE http://localhost:3333/characters/163b51b6-741e-4222-bce7-2b67a1d74f5f

