### Create characters
POST http://localhost:3333/characters
Content-Type: application/json

{
    "name": "veteran",
    "level": 3,
    "class": "warrior",
    "armor_class": 16,
    "hitpoints": 30,
    "attributes": {
       "for": 10,
       "dex": 12,
       "con": 14,
       "int": 16,
       "wis": 8,
       "car": 18
}
}

### List characters
GET https://ded-companion.onrender.com/characters

### Search usign Quey parameters

GET https://ded-companion.onrender.com/characters?search=newbie

### Update Character

PUT https://ded-companion.onrender.com/characters/163b51b6-741e-4222-bce7-2b67a1d74f5f
Content-Type: application/json

{
  "name": "Veteran",
  "level": 3,
  "class": "Warrior"
}

### Delete Character

DELETE https://ded-companion.onrender.com/characters/79e818ab-a105-42bc-9e21-8f4965fe6f40

